name: blink_app
description: A financial management and Cash advance app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.16
  smooth_page_indicator: ^1.2.0+3
  animated_text_kit: ^4.2.2
  url_launcher: ^6.3.1
  plaid_flutter: ^4.1.1
  http: ^1.2.2
  logger: ^2.5.0
  shared_preferences: ^2.3.3
  flutter_dotenv: ^5.2.1
  provider: ^6.1.2
  path_provider: ^2.1.5
  encrypt_shared_preferences: ^0.8.1
  cached_network_image: ^3.4.1
  sentry_flutter: ^8.10.1
  animate_do: ^3.3.4
  confetti: ^0.8.0
  intl: ^0.20.1
  flutter_shake_animated: ^0.0.5
  fl_chart: ^0.69.2
  get_it: ^8.0.2
  package_info_plus: ^8.1.2
  flutter_haptic: ^0.0.3
  flutter_localization: ^0.2.3
  flutter_chat_bubble: ^2.0.2
  shimmer: ^3.0.0
  lottie: ^3.3.0
  animated_emoji: ^3.1.0
  giffy_dialog: ^2.3.0
  flutter_animation_progress_bar: ^2.3.1
  flutter_animate: ^4.5.2
  uuid: ^4.5.1
  simple_animations: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  bloc_test: ^9.1.7

dependency_overrides:
  intl: ^0.20.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/animations/
    # Animated Emoji Assets
    - packages/animated_emoji/lottie/moneyWithWings.json
    - packages/animated_emoji/lottie/partyPopper.json
    - packages/animated_emoji/lottie/checkMark.json
    - packages/animated_emoji/lottie/sad.json
    - packages/animated_emoji/lottie/thinkingFace.json
    - packages/animated_emoji/lottie/rocket.json
    - packages/animated_emoji/lottie/alarmClock.json
    - packages/animated_emoji/lottie/electricity.json
  
  fonts:
    - family: Onest
      fonts:
        - asset: assets/fonts/Onest-Regular.ttf
        - asset: assets/fonts/Onest-Bold.ttf
        - asset: assets/fonts/NunitoSans_SemiBold.ttf
        - asset: assets/fonts/NunitoSans.ttf
          weight: 700
