import 'package:flutter/material.dart';
import 'transaction_category.dart';

/// Provides default categories for the application
class DefaultCategories {
  /// Get all default categories
  static List<TransactionCategory> get all => [
        ...essential,
        ...lifestyle,
        ...transportation,
        ...financial,
        ...income,
        ...education,
      ];

  /// Essential categories
  static List<TransactionCategory> get essential => [
        TransactionCategory(
          id: 'housing',
          name: 'Housing & Utilities',
          level: CategoryLevel.main,
          type: CategoryType.essential,
          color: Colors.blue[700]!,
          icon: Icons.home,
          createdAt: DateTime.now(),
          aliases: ['rent', 'mortgage', 'utilities', 'housing'],
        ),
        TransactionCategory(
          id: 'rent',
          name: 'Rent/Mortgage',
          parentId: 'housing',
          level: CategoryLevel.sub,
          type: CategoryType.essential,
          color: Colors.blue[600]!,
          icon: Icons.house,
          createdAt: DateTime.now(),
          aliases: ['rent payment', 'mortgage payment', 'lease'],
        ),
        TransactionCategory(
          id: 'utilities',
          name: 'Utilities',
          parentId: 'housing',
          level: CategoryLevel.sub,
          type: CategoryType.essential,
          color: Colors.blue[500]!,
          icon: Icons.power,
          createdAt: DateTime.now(),
          aliases: ['electricity', 'water', 'gas', 'internet', 'phone'],
        ),
        TransactionCategory(
          id: 'home_services',
          name: 'Home Services',
          parentId: 'housing',
          level: CategoryLevel.sub,
          type: CategoryType.essential,
          color: Colors.blue[400]!,
          icon: Icons.home_repair_service,
          createdAt: DateTime.now(),
          aliases: ['maintenance', 'repairs', 'cleaning'],
        ),
        TransactionCategory(
          id: 'healthcare',
          name: 'Healthcare',
          level: CategoryLevel.main,
          type: CategoryType.essential,
          color: Colors.red[700]!,
          icon: Icons.local_hospital,
          createdAt: DateTime.now(),
          aliases: ['health', 'medical', 'doctor'],
        ),
        TransactionCategory(
          id: 'medical',
          name: 'Medical',
          parentId: 'healthcare',
          level: CategoryLevel.sub,
          type: CategoryType.essential,
          color: Colors.red[600]!,
          icon: Icons.medical_services,
          createdAt: DateTime.now(),
          aliases: ['doctor', 'hospital', 'clinic'],
        ),
        TransactionCategory(
          id: 'pharmacy',
          name: 'Pharmacy',
          parentId: 'healthcare',
          level: CategoryLevel.sub,
          type: CategoryType.essential,
          color: Colors.red[500]!,
          icon: Icons.local_pharmacy,
          createdAt: DateTime.now(),
          aliases: ['medicine', 'prescription', 'drugs'],
        ),
        TransactionCategory(
          id: 'health_insurance',
          name: 'Health Insurance',
          parentId: 'healthcare',
          level: CategoryLevel.sub,
          type: CategoryType.essential,
          color: Colors.red[400]!,
          icon: Icons.health_and_safety,
          createdAt: DateTime.now(),
          aliases: ['insurance', 'coverage'],
        ),
        TransactionCategory(
          id: 'groceries',
          name: 'Groceries',
          level: CategoryLevel.main,
          type: CategoryType.essential,
          color: Colors.green[700]!,
          icon: Icons.shopping_cart,
          createdAt: DateTime.now(),
          aliases: ['supermarket', 'food', 'grocery'],
        ),
      ];

  /// Lifestyle categories
  static List<TransactionCategory> get lifestyle => [
        TransactionCategory(
          id: 'dining',
          name: 'Dining & Drinks',
          level: CategoryLevel.main,
          type: CategoryType.lifestyle,
          color: Colors.orange[700]!,
          icon: Icons.restaurant,
          createdAt: DateTime.now(),
          aliases: ['food', 'restaurant', 'dining'],
        ),
        TransactionCategory(
          id: 'restaurants',
          name: 'Restaurants',
          parentId: 'dining',
          level: CategoryLevel.sub,
          type: CategoryType.lifestyle,
          color: Colors.orange[600]!,
          icon: Icons.restaurant_menu,
          createdAt: DateTime.now(),
          aliases: ['dining', 'food'],
        ),
        TransactionCategory(
          id: 'cafes',
          name: 'Cafes',
          parentId: 'dining',
          level: CategoryLevel.sub,
          type: CategoryType.lifestyle,
          color: Colors.orange[500]!,
          icon: Icons.coffee,
          createdAt: DateTime.now(),
          aliases: ['coffee', 'cafe', 'bakery'],
        ),
        TransactionCategory(
          id: 'bars',
          name: 'Bars',
          parentId: 'dining',
          level: CategoryLevel.sub,
          type: CategoryType.lifestyle,
          color: Colors.orange[400]!,
          icon: Icons.local_bar,
          createdAt: DateTime.now(),
          aliases: ['bar', 'pub', 'alcohol'],
        ),
        TransactionCategory(
          id: 'shopping',
          name: 'Shopping',
          level: CategoryLevel.main,
          type: CategoryType.lifestyle,
          color: Colors.purple[700]!,
          icon: Icons.shopping_bag,
          createdAt: DateTime.now(),
          aliases: ['shopping', 'retail', 'store'],
        ),
        TransactionCategory(
          id: 'clothing',
          name: 'Clothing',
          parentId: 'shopping',
          level: CategoryLevel.sub,
          type: CategoryType.lifestyle,
          color: Colors.purple[600]!,
          icon: Icons.checkroom,
          createdAt: DateTime.now(),
          aliases: ['clothes', 'apparel', 'fashion'],
        ),
        TransactionCategory(
          id: 'electronics',
          name: 'Electronics',
          parentId: 'shopping',
          level: CategoryLevel.sub,
          type: CategoryType.lifestyle,
          color: Colors.purple[500]!,
          icon: Icons.devices,
          createdAt: DateTime.now(),
          aliases: ['electronics', 'gadgets', 'technology'],
        ),
        TransactionCategory(
          id: 'entertainment',
          name: 'Entertainment',
          level: CategoryLevel.main,
          type: CategoryType.lifestyle,
          color: Colors.indigo[700]!,
          icon: Icons.movie,
          createdAt: DateTime.now(),
          aliases: ['entertainment', 'fun', 'leisure'],
        ),
        TransactionCategory(
          id: 'movies',
          name: 'Movies & Shows',
          parentId: 'entertainment',
          level: CategoryLevel.sub,
          type: CategoryType.lifestyle,
          color: Colors.indigo[600]!,
          icon: Icons.movie_creation,
          createdAt: DateTime.now(),
          aliases: ['movies', 'cinema', 'theater'],
        ),
        TransactionCategory(
          id: 'games',
          name: 'Games',
          parentId: 'entertainment',
          level: CategoryLevel.sub,
          type: CategoryType.lifestyle,
          color: Colors.indigo[500]!,
          icon: Icons.games,
          createdAt: DateTime.now(),
          aliases: ['games', 'gaming', 'video games'],
        ),
      ];

  /// Transportation categories
  static List<TransactionCategory> get transportation => [
        TransactionCategory(
          id: 'transport',
          name: 'Transportation',
          level: CategoryLevel.main,
          type: CategoryType.transportation,
          color: Colors.teal[700]!,
          icon: Icons.directions_car,
          createdAt: DateTime.now(),
          aliases: ['transport', 'travel', 'commute'],
        ),
        TransactionCategory(
          id: 'public_transit',
          name: 'Public Transit',
          parentId: 'transport',
          level: CategoryLevel.sub,
          type: CategoryType.transportation,
          color: Colors.teal[600]!,
          icon: Icons.directions_bus,
          createdAt: DateTime.now(),
          aliases: ['bus', 'train', 'subway', 'metro'],
        ),
        TransactionCategory(
          id: 'ride_services',
          name: 'Ride Services',
          parentId: 'transport',
          level: CategoryLevel.sub,
          type: CategoryType.transportation,
          color: Colors.teal[500]!,
          icon: Icons.local_taxi,
          createdAt: DateTime.now(),
          aliases: ['uber', 'lyft', 'taxi', 'cab'],
        ),
      ];

  /// Financial categories
  static List<TransactionCategory> get financial => [
        TransactionCategory(
          id: 'financial',
          name: 'Financial',
          level: CategoryLevel.main,
          type: CategoryType.financial,
          color: Colors.grey[700]!,
          icon: Icons.account_balance,
          createdAt: DateTime.now(),
          aliases: ['financial', 'finance', 'money'],
        ),
        TransactionCategory(
          id: 'investments',
          name: 'Investments',
          parentId: 'financial',
          level: CategoryLevel.sub,
          type: CategoryType.financial,
          color: Colors.grey[600]!,
          icon: Icons.trending_up,
          createdAt: DateTime.now(),
          aliases: ['investment', 'stocks', 'crypto'],
        ),
        TransactionCategory(
          id: 'insurance',
          name: 'Insurance',
          parentId: 'financial',
          level: CategoryLevel.sub,
          type: CategoryType.financial,
          color: Colors.grey[500]!,
          icon: Icons.security,
          createdAt: DateTime.now(),
          aliases: ['insurance', 'coverage', 'protection'],
        ),
      ];

  /// Income categories
  static List<TransactionCategory> get income => [
        TransactionCategory(
          id: 'income',
          name: 'Income',
          level: CategoryLevel.main,
          type: CategoryType.income,
          color: Colors.green[700]!,
          icon: Icons.payments,
          createdAt: DateTime.now(),
          aliases: ['income', 'earnings', 'revenue'],
        ),
        TransactionCategory(
          id: 'salary',
          name: 'Salary',
          parentId: 'income',
          level: CategoryLevel.sub,
          type: CategoryType.income,
          color: Colors.green[600]!,
          icon: Icons.work,
          createdAt: DateTime.now(),
          aliases: ['salary', 'paycheck', 'wages'],
        ),
        TransactionCategory(
          id: 'freelance',
          name: 'Freelance',
          parentId: 'income',
          level: CategoryLevel.sub,
          type: CategoryType.income,
          color: Colors.green[500]!,
          icon: Icons.computer,
          createdAt: DateTime.now(),
          aliases: ['freelance', 'contract', 'gig'],
        ),
      ];

  /// Education categories
  static List<TransactionCategory> get education => [
        TransactionCategory(
          id: 'education',
          name: 'Education',
          level: CategoryLevel.main,
          type: CategoryType.education,
          color: Colors.brown[700]!,
          icon: Icons.school,
          createdAt: DateTime.now(),
          aliases: ['education', 'learning', 'school'],
        ),
        TransactionCategory(
          id: 'tuition',
          name: 'Tuition',
          parentId: 'education',
          level: CategoryLevel.sub,
          type: CategoryType.education,
          color: Colors.brown[600]!,
          icon: Icons.payment,
          createdAt: DateTime.now(),
          aliases: ['tuition', 'fees', 'college'],
        ),
        TransactionCategory(
          id: 'books',
          name: 'Books & Supplies',
          parentId: 'education',
          level: CategoryLevel.sub,
          type: CategoryType.education,
          color: Colors.brown[500]!,
          icon: Icons.book,
          createdAt: DateTime.now(),
          aliases: ['books', 'supplies', 'materials'],
        ),
      ];
}
